# NOTE: Do not edit, file was generated by jhconvert

Name: sugar-etoys-activity
Version: 102
Release: %mkrel 1
Summary: Squeak Etoys activity for Sugar
License: MIT/Apache
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/fructose/Etoys/etoys-activity-102.tar.gz

Requires: etoys >= 4.0.2229
Requires: sugar-toolkit >= 0.85.3

BuildRequires: sugar-toolkit >= 0.85.3

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch: noarch

%description
Squeak Etoys was inspired by LOGO, PARC-Smalltalk, Hypercard, starLOGO
and AgentSheets. It is a media-rich authoring environment with a simple,
powerful scripted object model for many kinds of objects created by end-users
that runs on many platforms, and it is free and open source. It includes 2D and
3D graphics, images, text, particles, presentations, web-pages, videos, sound
and MIDI, etc. It includes the ability to share desktops with other Etoy users
in real-time, so many forms of immersive mentoring and play can be done over
the Internet.

%prep
%setup -q -n etoys-activity-102


%build

rm -f MANIFEST
python setup.py build

%install
rm -rf %{buildroot}
python setup.py install --prefix=%{buildroot}/%{_prefix}
find %{buildroot} -name '*.py.orig' -print0 | xargs -0 rm -f


%clean
rm -rf %{buildroot}

%files 
%defattr(-,root,root,-)
%{_datadir}/sugar/activities/*
%doc COPYING NEWS

